# remaps.py ---

# Copyright (C) 2022  Munyoki Kilyungi <bonface.kilyungi@strathmore.edu>
# Copyright (C) 2022  Gertrude Gichuhi <ggichuhi@strathmore.edu>
# Copyright (C) 2022  Eunice Wanyoike <eunice.wanyoike@strathmore.edu>
# Copyright (C) 2022  Peter Mburu <nyambura.peter@strathmore.edu>
# Copyright (C) 2022  Beatrice Ngeno <beatrice.ngeno@strathmore.edu>

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

COLUMNS_REMAP = {
    "Total years of experience": "Experience (Years)",
    "Your main technology / programming language": "PL",
    "Other technologies/programming languages you use often": "PL (Other)",
    "Yearly brutto salary (without bonus and stocks) in EUR": "Salary (2020)",
    "Yearly bonus + stocks in EUR": "Bonus (2020)",
    "Annual brutto salary (without bonus and stocks) one year ago. Only answer if staying in the same country": "Salary (2019)",
    "Number of vacation days": "Vacation (days)",
    "Annual bonus+stocks one year ago. Only answer if staying in same country": "Bonus+Stocks (2019)",
    "Main language at work": "Language (Work)",
    "Position ": "Position",
    "Have you lost your job due to the coronavirus outbreak?": "Job Loss? (COVID)",
    "Have you been forced to have a shorter working week (Kurzarbeit)? If yes, how many hours per week": "Shorter Work Week (hrs/week)",
    "Have you received additional monetary support from your employer due to Work From Home? If yes, how much in 2020 in EUR": "Extra perks (2020)",
}


PL_REMAP = {
    ".NET": ".Net",
    ".Net": ".Net",
    ".Net, Angular": ".Net",
    ".net": ".Net",
    ".net, c++, spss, embeddded": ".Net",
    "ABAP": "Others",
    "AI": "Python",
    "AWS": "Others",
    "AWS, GCP, Python,K8s": "Others",
    "Agile": "Others",
    "Android": "Others",
    "Android/Kotlin": "Others",
    "Angular": "Others",
    "Angular, React": "Others",
    "Angular, TypeScript": "Others",
    "Angular, Typescript": "Others",
    "Apache Spark": "Others",
    "Apotheker": "Others",
    "Atlassian JIRA": "Others",
    "Autonomous Driving": "Others",
    "Aws Hadoop Postgre Typescript": "Others",
    "Azure": "Others",
    "Azure, SAP": "Others",
    "BI, DWH, ETL/ELT": "Others",
    "Bash": "Others",
    "Blockchain": "Others",
    "Business Development Manager Operation ": "Others",
    "C": "Others",
    "C#": "Others",
    "C# .NET": "Others",
    "C#, .net core": "Others",
    "C#/.NET": "Others",
    "C++": "C++",
    "C++, C#": "C++",
    "C++, Java, Embedded C": "C++",
    "C++/C#": "C++",
    "C++/c": "C++",
    "C, C++": "C++",
    "C, Matlab": "Others",
    "C/C++": "C++",
    "Charles": "Others",
    "Clojure": "Others",
    "Cloud": "Others",
    "Cobol": "Others",
    "Computer Networking,  Network Security ": "Others",
    "DC Management": "Others",
    "DWH": "Others",
    "DevOps": "Others",
    "Django, Flask, Plotly Dash": "Python",
    "Elixir": "Others",
    "Embedded": "Others",
    "Embedded C++": "Others",
    "Erlang": "Others",
    "FBD": "Others",
    "Figma": "Others",
    "Frontend": "Others",
    "Frontend: react, node.js": "Others",
    "GCP": "Others",
    "Go": "Others",
    "Go, PHP, SQL": "Others",
    "Go/Python": "Python",
    "Golang": "Others",
    "Golang ": "Others",
    "Google Cloud Platform": "Others",
    "Grails, Groovy": "Others",
    "Hardware": "Others",
    "Haskell": "Others",
    "JAVA": "Java",
    "JS": "JavScript",
    "JS, Java": "JavScript",
    "JS, WDIO": "JavScript",
    "JavScript": "JavScript",
    "Java": "Java",
    "Java ": "Java",
    "Java & Distributed Systems Stuff": "Java",
    "Java & PHP": "Java",
    "Java / Scala": "Java",
    "Java Backend": "Java",
    "Java, .Net": "Java",
    "Java, JS": "Java",
    "Java, JavaScript": "Java",
    "Java, Javascript": "Java",
    "Java, Kotlin": "Java",
    "Java, angular, Aws": "Java",
    "Java, terraform": "Java",
    "Java/C++": "Java",
    "Java/Groovy": "Java",
    "Java/Kotlin": "Java",
    "Java/Scala": "Java",
    "JavaScript": "JavaScript",
    "JavaScript ": "JavaScript",
    "JavaScript / TypeScript": "JavaScript",
    "JavaScript / typescript": "JavaScript",
    "JavaScript, TypeScript": "JavaScript",
    "JavaScript/ES6": "JavaScript",
    "JavaScript/TypeScript": "JavaScript",
    "JavaScript/Typescript": "JavaScript",
    "Javascript": "JavaScript",
    "Javascript ": "JavaScript",
    "Javascript / Typescript": "JavaScript",
    "Javascript, Angular": "JavaScript",
    "Javascript/Typescript": "JavaScript",
    "Jira": "Other",
    "Js": "JavaScript",
    "Js, TypeScript, Angular": "JavaScript",
    "Js, reactJS ": "JavaScript",
    "Kotlin": "Other",
    "Kotlin ": "Other",
    "Kotlin, Java": "Other",
    "Kotlin/PHP": "Other",
    "Kuberenetes, Openstack": "Other",
    "Kubernetes": "Other",
    "Kubernetes, Terraform, GCP": "Other",
    "Kubrrnetes": "Other",
    "Linux": "Other",
    "Linux Kernel": "Other",
    "Linux/UNIX, GIT, Virtualisation Platforms, *shell(s) scripts": "Other",
    "ML": "Python",
    "Magento": "Other",
    "Management": "Other",
    "Ml/Python": "Python",
    "NLP, Python": "Python",
    "Network": "Other",
    "Network Automation": "Other",
    "Node": "Other",
    "Node.js": "Other",
    "NodeJS": "Other",
    "NodeJS, Typescript, AWS": "Other",
    "NodeJS/TS": "Other",
    "Nodejs": "Other",
    "NodsJs": "Other",
    "Objective-C": "Other",
    "Oracle": "Other",
    "PHP": "Other",
    "PHP ": "Other",
    "PHP/MySQL": "Other",
    "PL/SQL": "Other",
    "PM tools": "Other",
    "PS, Sketch, React, CSS3": "Other",
    "Pascal, VB.NET, C#": "Other",
    "Pegasystems platform ": "Other",
    "Perl": "Other",
    "Php": "Other",
    "Power BI": "Other",
    "PowerShell": "Other",
    "Pyrhon": "Python",
    "Python": "Python",
    "Python ": "Python",
    "Python (Django)": "Python",
    "Python + SQL": "Python",
    "Python / JavaScript (React)": "Python",
    "Python, Pytorch": "Python",
    "Python, SQL": "Python",
    "Python, Whole Apache Data Science Stack, AWS": "Python",
    "Python, cloud computing ": "Python",
    "Python, database technologies": "Python",
    "Python, statistics, SQL": "Python",
    "Python/NLP": "Python",
    "Python/SQL": "Python",
    "QA": "Other",
    "Qlik": "Other",
    "Qlik BI Tool, SQL": "Other",
    "Qml": "Other",
    "R": "Python",
    "React": "React",
    "React ": "React",
    "React / JavaScript": "React",
    "React JS": "React",
    "React.js / TypeScript": "React",
    "React/Typescript": "React",
    "Ruby": "Other",
    "Ruby on Rails": "Other",
    "SAP": "Other",
    "SAP / ABAP": "Other",
    "SAP ABAP": "Other",
    "SAP BW / ABAP": "Other",
    "SAS,SQL,Python": "Python",
    "SQL": "Other",
    "SRE": "Other",
    "SWIFT": "Other",
    "Salesforce ": "Other",
    "Scala": "Other",
    "Scala / Python": "Python",
    "Scala, Apache Spark": "Other",
    "Scala, React.js": "Other",
    "Sketch, Figma": "Other",
    "Spark": "Other",
    "Spark, Pytorch": "Other",
    "Spring": "Other",
    "Sql": "Other",
    "Sql ": "Other",
    "Sql, BQ, tableau, gtm, ga": "Other",
    "Swift": "Other",
    "Swift, Objective-C": "Other",
    "Swift, Objective-C, iOS": "Other",
    "Swift, objective-c": "Other",
    "Swift/Kotlin": "Other",
    "T-SQL": "Other",
    "TS": "Other",
    "Terraform": "Other",
    "Terraform ": "Other",
    "Terraform, Kubernetes, AWS, GCP, Ansible, Puppet": "Other",
    "Test Management ": "Other",
    "Tricentis Tosca": "Other",
    "TypeScript": "JavaScript",
    "TypeScript, JavaScript": "JavaScript",
    "TypeScript, Kotlin": "JavaScript",
    "TypeScript, React": "JavaScript",
    "TypeScript/Angular": "JavaScript",
    "Typescript": "JavaScript",
    "Typescript ": "JavaScript",
    "Typescript / Angular": "JavaScript",
    "Typescript, Web apps": "JavaScript",
    "UML": "Other",
    "VB, RPA, Python": "Python",
    "VHDL": "Other",
    "Web": "Other",
    "Web developer": "JavaScript",
    "android": "Other",
    "c#": "Other",
    "c++": "C++",
    "c/c++": "C++",
    "consumer analysis": "Other",
    "embedded": "Other",
    "go": "Other",
    "golang": "Other",
    "iOS": "Other",
    "java": "Java",
    "java/scala/go/clouds/devops": "Java",
    "javascript": "JavaScript",
    "jenkins bash": "Other",
    "js": "JavaScript",
    "julia": "Other",
    "k8s": "Other",
    "kotlin": "Other",
    "networking, linux, automation, cloud": "Other",
    "none": "Other",
    "nothing": "Other",
    "php": "Other",
    "php, js, python, docker": "Python",
    "pythin": "Python",
    "python": "Python",
    "python ": "Python",
    "python, scala": "Python",
    "ruby on rails": "Other",
    "scala": "Other",
    "several": "Other",
    "spark": "Other",
    "sql": "Other",
    "swift": "Other",
    "typescript": "JavaScript",
    "yaml": "Other",
    "Офмф": "Other",
    "С#": "Other",
    "-": "Other",
    "--": "Other",
}
